# tasks/main.yml
- name: Ensure namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ postgres_namespace }}"
    state: present

- name: Deploy PostgreSQL headless service
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/postgres-service.yml.j2"

- name: Deploy PostgreSQL statefulset
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/postgres-statefulset.yml.j2"

- name: Create backup CronJob
  kubernetes.core.k8s:
    state: present
    namespace: "{{ postgres_namespace }}"
    template: "{{ role_path }}/templates/backup-cronjob.yml.j2"

